name: yka_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.1.0
  flutter_svg_provider: ^1.0.7
  outline_gradient_button: ^2.0.1+1
  google_maps_flutter: ^2.5.0
  sms_autofill: ^2.3.0
  carousel_slider: ^4.2.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansRomanBold.ttf
          weight: 700
        - asset: assets/fonts/OpenSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSansRomanExtraBold.ttf
          weight: 800
    - family: DM Sans
      fonts: 
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
        - asset: assets/fonts/DMSansBlack.ttf
          weight: 900
    - family: Rubik
      fonts: 
        - asset: assets/fonts/RubikRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RubikRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RubikRegular.ttf
          weight: 400
        - asset: assets/fonts/RubikRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/RubikMedium.ttf
          weight: 500
        - asset: assets/fonts/RubikRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RubikRomanBold.ttf
          weight: 700
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
