import 'bloc/profile_three_bloc.dart';import 'models/profile_three_model.dart';import 'package:country_pickers/country.dart';import 'package:country_pickers/country_pickers.dart';import 'package:flutter/material.dart';import 'package:yka_app/core/app_export.dart';import 'package:yka_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:yka_app/widgets/app_bar/custom_app_bar.dart';import 'package:yka_app/widgets/custom_elevated_button.dart';import 'package:yka_app/widgets/custom_phone_number.dart';import 'package:yka_app/widgets/custom_text_form_field.dart';class ProfileThreeScreen extends StatelessWidget {const ProfileThreeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ProfileThreeBloc>(create: (context) => ProfileThreeBloc(ProfileThreeState(profileThreeModelObj: ProfileThreeModel()))..add(ProfileThreeInitialEvent()), child: ProfileThreeScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 36.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Container(width: 240.h, margin: EdgeInsets.only(left: 20.h), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_enter_the".tr, style: CustomTextStyles.headlineSmallRegular), TextSpan(text: "msg_number_to_reset".tr, style: theme.textTheme.headlineSmall)]), textAlign: TextAlign.left))), SizedBox(height: 7.v), Align(alignment: Alignment.centerLeft, child: Container(width: 337.h, margin: EdgeInsets.only(left: 20.h, right: 35.h), child: Text("msg_create_a_4_digit".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall!.copyWith(height: 1.57)))), SizedBox(height: 26.v), Padding(padding: EdgeInsets.only(left: 20.h, right: 25.h), child: BlocBuilder<ProfileThreeBloc, ProfileThreeState>(builder: (context, state) {return CustomPhoneNumber(country: state.selectedCountry ?? CountryPickerUtils.getCountryByPhoneCode('1'), controller: state.phoneNumberController, onTap: (Country value) {context.read<ProfileThreeBloc>().add(ChangeCountryEvent(value: value));});})), SizedBox(height: 16.v), Padding(padding: EdgeInsets.symmetric(horizontal: 20.h), child: BlocSelector<ProfileThreeBloc, ProfileThreeState, TextEditingController?>(selector: (state) => state.cprController, builder: (context, cprController) {return CustomTextFormField(controller: cprController, hintText: "lbl_cpr".tr, textInputAction: TextInputAction.done, borderDecoration: TextFormFieldStyleHelper.fillWhiteA, fillColor: appTheme.whiteA700);})), SizedBox(height: 49.v), CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.symmetric(horizontal: 20.h), buttonStyle: CustomButtonStyles.fillIndigoTL13), SizedBox(height: 243.v), _buildColumn(context)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.fromLTRB(20.h, 3.v, 325.h, 3.v), onTap: () {onTapClose(context);})); } 
/// Section Widget
Widget _buildColumn(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 139.h, vertical: 26.v), decoration: AppDecoration.fillWhiteA700, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_app_version_4_4_9".tr.toUpperCase(), style: CustomTextStyles.labelMediumProximaNovaAlt)])); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
