import 'bloc/profile_seven_bloc.dart';import 'models/profile_seven_model.dart';import 'package:country_pickers/country.dart';import 'package:country_pickers/country_pickers.dart';import 'package:flutter/material.dart';import 'package:yka_app/core/app_export.dart';import 'package:yka_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:yka_app/widgets/app_bar/custom_app_bar.dart';import 'package:yka_app/widgets/custom_elevated_button.dart';import 'package:yka_app/widgets/custom_phone_number.dart';class ProfileSevenScreen extends StatelessWidget {const ProfileSevenScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ProfileSevenBloc>(create: (context) => ProfileSevenBloc(ProfileSevenState(profileSevenModelObj: ProfileSevenModel()))..add(ProfileSevenInitialEvent()), child: ProfileSevenScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 36.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: SizedBox(width: 240.h, child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_enter_the".tr, style: CustomTextStyles.headlineSmallRegular), TextSpan(text: "msg_number_to_reset".tr, style: theme.textTheme.headlineSmall)]), textAlign: TextAlign.left))), SizedBox(height: 7.v), Align(alignment: Alignment.centerLeft, child: Container(width: 337.h, margin: EdgeInsets.only(right: 15.h), child: Text("msg_create_a_4_digit".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall!.copyWith(height: 1.57)))), SizedBox(height: 26.v), BlocBuilder<ProfileSevenBloc, ProfileSevenState>(builder: (context, state) {return CustomPhoneNumber(country: state.selectedCountry ?? CountryPickerUtils.getCountryByPhoneCode('1'), controller: state.phoneNumberController, onTap: (Country value) {context.read<ProfileSevenBloc>().add(ChangeCountryEvent(value: value));});}), SizedBox(height: 16.v), _buildColumn(context), SizedBox(height: 49.v), _buildStack(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildColumn1(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.fromLTRB(20.h, 3.v, 325.h, 3.v), onTap: () {onTapClose(context);})); } 
/// Section Widget
Widget _buildColumn(BuildContext context) { return Container(width: 353.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 8.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.2, child: Text("lbl_cpr".tr, style: CustomTextStyles.labelLargeBlack90005_1)), SizedBox(height: 3.v), Text("lbl_987_765_6541".tr, style: CustomTextStyles.titleMediumSemiBold)])); } 
/// Section Widget
Widget _buildStack(BuildContext context) { return SizedBox(height: 68.v, width: 353.h, child: Stack(alignment: Alignment.topCenter, children: [Opacity(opacity: 0.2, child: Align(alignment: Alignment.bottomCenter, child: Container(height: 54.v, width: 313.h, decoration: BoxDecoration(color: theme.colorScheme.primary.withOpacity(0.42), borderRadius: BorderRadius.circular(4.h))))), CustomElevatedButton(width: 353.h, text: "lbl_continue".tr, alignment: Alignment.topCenter)])); } 
/// Section Widget
Widget _buildColumn1(BuildContext context) { return Container(margin: EdgeInsets.only(left: 139.h, right: 151.h, bottom: 26.v), decoration: AppDecoration.fillWhiteA700, child: Text("msg_app_version_4_4_9".tr.toUpperCase(), style: CustomTextStyles.labelMediumProximaNovaAlt)); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
