import 'bloc/profile_fifty_bloc.dart';import 'models/profile_fifty_model.dart';import 'package:flutter/material.dart';import 'package:yka_app/core/app_export.dart';import 'package:yka_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:yka_app/widgets/app_bar/custom_app_bar.dart';import 'package:yka_app/widgets/custom_elevated_button.dart';import 'package:yka_app/widgets/custom_floating_text_field.dart';class ProfileFiftyScreen extends StatelessWidget {const ProfileFiftyScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ProfileFiftyBloc>(create: (context) => ProfileFiftyBloc(ProfileFiftyState(profileFiftyModelObj: ProfileFiftyModel()))..add(ProfileFiftyInitialEvent()), child: ProfileFiftyScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<ProfileFiftyBloc, ProfileFiftyState>(builder: (context, state) {return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 35.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: SizedBox(width: 193.h, child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_submit_your".tr, style: CustomTextStyles.headlineSmallRegular), TextSpan(text: "lbl_car_information".tr, style: theme.textTheme.headlineSmall)]), textAlign: TextAlign.left))), SizedBox(height: 13.v), Text("msg_let_us_know_about".tr, style: theme.textTheme.titleSmall), SizedBox(height: 39.v), _buildFloatingTextField(context), SizedBox(height: 16.v), _buildFloatingTextField1(context), SizedBox(height: 16.v), _buildZipcode(context), SizedBox(height: 16.v), _buildFloatingTextField3(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildAddVehicle(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.fromLTRB(20.h, 3.v, 325.h, 3.v), onTap: () {onTapClose(context);})); } 
/// Section Widget
Widget _buildFloatingTextField(BuildContext context) { return BlocSelector<ProfileFiftyBloc, ProfileFiftyState, TextEditingController?>(selector: (state) => state.floatingTextFieldController, builder: (context, floatingTextFieldController) {return CustomFloatingTextField(controller: floatingTextFieldController, labelText: "lbl_vrn2".tr, labelStyle: CustomTextStyles.titleMediumSemiBold, hintText: "lbl_vrn2".tr);}); } 
/// Section Widget
Widget _buildFloatingTextField1(BuildContext context) { return BlocSelector<ProfileFiftyBloc, ProfileFiftyState, TextEditingController?>(selector: (state) => state.floatingTextFieldController1, builder: (context, floatingTextFieldController1) {return CustomFloatingTextField(controller: floatingTextFieldController1, labelText: "lbl_vin".tr, labelStyle: CustomTextStyles.titleMediumSemiBold, hintText: "lbl_vin".tr);}); } 
/// Section Widget
Widget _buildFloatingTextField2(BuildContext context) { return BlocSelector<ProfileFiftyBloc, ProfileFiftyState, TextEditingController?>(selector: (state) => state.floatingTextFieldController2, builder: (context, floatingTextFieldController2) {return CustomFloatingTextField(width: 37.h, controller: floatingTextFieldController2, labelText: "lbl_gcc".tr, labelStyle: CustomTextStyles.titleMediumSemiBold, hintText: "lbl_gcc".tr, contentPadding: EdgeInsets.only(top: 20.v), borderDecoration: FloatingTextFormFieldStyleHelper.custom, filled: false);}); } 
/// Section Widget
Widget _buildZipcode(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 8.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [_buildFloatingTextField2(context), Padding(padding: EdgeInsets.only(top: 20.v, right: 4.h), child: Text("lbl_km".tr, style: CustomTextStyles.titleMedium_1))])); } 
/// Section Widget
Widget _buildFloatingTextField3(BuildContext context) { return BlocSelector<ProfileFiftyBloc, ProfileFiftyState, TextEditingController?>(selector: (state) => state.floatingTextFieldController3, builder: (context, floatingTextFieldController3) {return CustomFloatingTextField(controller: floatingTextFieldController3, labelText: "lbl_year".tr, labelStyle: CustomTextStyles.titleMediumSemiBold, hintText: "lbl_year".tr, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.symmetric(horizontal: 24.h), child: CustomImageView(imagePath: ImageConstant.imgArrowdownRed800, height: 4.v, width: 8.h)), suffixConstraints: BoxConstraints(maxHeight: 59.v));}); } 
/// Section Widget
Widget _buildButton(BuildContext context) { return CustomElevatedButton(width: 353.h, text: "lbl_add_vehicle".tr, alignment: Alignment.topCenter); } 
/// Section Widget
Widget _buildAddVehicle(BuildContext context) { return Container(height: 68.v, width: 353.h, margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 20.v), child: Stack(alignment: Alignment.topCenter, children: [Opacity(opacity: 0.2, child: Align(alignment: Alignment.bottomCenter, child: Container(height: 54.v, width: 313.h, decoration: BoxDecoration(color: theme.colorScheme.primary.withOpacity(0.42), borderRadius: BorderRadius.circular(4.h))))), _buildButton(context)])); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
