import 'bloc/profile_four_bloc.dart';import 'models/profile_four_model.dart';import 'package:flutter/material.dart';import 'package:yka_app/core/app_export.dart';import 'package:yka_app/core/utils/validation_functions.dart';import 'package:yka_app/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:yka_app/widgets/app_bar/custom_app_bar.dart';import 'package:yka_app/widgets/custom_elevated_button.dart';import 'package:yka_app/widgets/custom_floating_text_field.dart';
// ignore_for_file: must_be_immutable
class ProfileFourScreen extends StatelessWidget {ProfileFourScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<ProfileFourBloc>(create: (context) => ProfileFourBloc(ProfileFourState(profileFourModelObj: ProfileFourModel()))..add(ProfileFourInitialEvent()), child: ProfileFourScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<ProfileFourBloc, ProfileFourState>(builder: (context, state) {return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 36.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: SizedBox(width: 132.h, child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_create_your".tr, style: CustomTextStyles.headlineSmallRegular), TextSpan(text: "lbl_profile2".tr, style: theme.textTheme.headlineSmall)]), textAlign: TextAlign.left))), SizedBox(height: 13.v), Text("msg_let_us_know_about".tr, style: theme.textTheme.titleSmall), SizedBox(height: 39.v), _buildFirstNameField(context), SizedBox(height: 12.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Row(children: [Container(height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(bottom: 2.v), padding: EdgeInsets.symmetric(horizontal: 6.h, vertical: 3.v), decoration: AppDecoration.fillRed70003.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.img, height: 8.v, width: 2.h, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_you_can_t_use".tr, style: CustomTextStyles.bodySmallOpenSansRed70003))]))), SizedBox(height: 13.v), _buildLastNameField(context), SizedBox(height: 16.v), _buildZipcodeField(context), SizedBox(height: 16.v), _buildCarDetailsRow(context), SizedBox(height: 5.v)]))), bottomNavigationBar: _buildContinueStack(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.fromLTRB(20.h, 3.v, 325.h, 3.v), onTap: () {onTapClose(context);})); } 
/// Section Widget
Widget _buildFirstNameField(BuildContext context) { return BlocSelector<ProfileFourBloc, ProfileFourState, TextEditingController?>(selector: (state) => state.firstNameFieldController, builder: (context, firstNameFieldController) {return CustomFloatingTextField(controller: firstNameFieldController, labelText: "lbl_first_name".tr, labelStyle: CustomTextStyles.titleMediumSemiBold, hintText: "lbl_first_name".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}); } 
/// Section Widget
Widget _buildLastNameField(BuildContext context) { return BlocSelector<ProfileFourBloc, ProfileFourState, TextEditingController?>(selector: (state) => state.lastNameFieldController, builder: (context, lastNameFieldController) {return CustomFloatingTextField(controller: lastNameFieldController, labelText: "lbl_last_name".tr, labelStyle: CustomTextStyles.titleMediumSemiBold, hintText: "lbl_last_name".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}); } 
/// Section Widget
Widget _buildZipcodeField(BuildContext context) { return BlocSelector<ProfileFourBloc, ProfileFourState, TextEditingController?>(selector: (state) => state.zipcodeFieldController, builder: (context, zipcodeFieldController) {return CustomFloatingTextField(controller: zipcodeFieldController, labelText: "lbl_zip_code".tr, labelStyle: CustomTextStyles.titleSmallBlack90005, hintText: "lbl_zip_code".tr, hintStyle: CustomTextStyles.titleSmallBlack90005, textInputAction: TextInputAction.done, textInputType: TextInputType.number, validator: (value) {if (!isNumeric(value)) {return "err_msg_please_enter_valid_number".tr;} return null;}, contentPadding: EdgeInsets.fromLTRB(20.h, 20.v, 20.h, 18.v));}); } 
/// Section Widget
Widget _buildCarDetailsRow(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 19.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_add_your_car_details".tr, style: CustomTextStyles.titleSmallPrimary_1), CustomImageView(imagePath: ImageConstant.imgArrowRightPrimary, height: 12.v, width: 15.h, margin: EdgeInsets.only(top: 4.v, right: 12.h, bottom: 3.v))])); } 
/// Section Widget
Widget _buildContinue(BuildContext context) { return CustomElevatedButton(width: 353.h, text: "lbl_continue".tr, alignment: Alignment.topCenter); } 
/// Section Widget
Widget _buildContinueStack(BuildContext context) { return Container(height: 68.v, width: 353.h, margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 20.v), child: Stack(alignment: Alignment.topCenter, children: [Opacity(opacity: 0.2, child: Align(alignment: Alignment.bottomCenter, child: Container(height: 54.v, width: 313.h, decoration: BoxDecoration(color: theme.colorScheme.primary.withOpacity(0.42), borderRadius: BorderRadius.circular(4.h))))), _buildContinue(context)])); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
